[package]
name = "wi-store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
hex.workspace = true
thiserror.workspace = true
wwav-ids.workspace = true

[dev-dependencies]
rand.workspace = true
tempfile.workspace = true
