import { useState } from 'react';
import { ArrowLeft, Check, MessageSquare } from 'lucide-react';
import { api, errorText, type Document } from '../client';
import { image, type ImageProposal } from './client';
export function ImageClaude({ document: d, dirty, onApplied }: { document: Document; dirty: boolean; onApplied(): Promise<void> }) {
  const [intent, setIntent] = useState('adjust'); const [prompt, setPrompt] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [answer, setAnswer] = useState(''); const [proposal, setProposal] = useState<ImageProposal | null>(null);
  const ask = async () => { setBusy(true); setError(''); setProposal(null); try { const r = await image.read(d.id); const result = await image.assist(d.id, r.base, r.view.layer ?? r.image.layers[0].id, intent, prompt); setAnswer(result.answer); setProposal(result.proposal); } catch (e) { setError(errorText(e)); } finally { setBusy(false); } };
  const apply = async () => { if (!proposal) return; setBusy(true); try { await api.apply(proposal.id); setProposal(null); await onApplied(); setAnswer(proposal.command === 'console.image.selection' ? 'Selection applied.' : 'Applied as a new version.'); } catch (e) { setError(errorText(e)); } finally { setBusy(false); } };
  return <div className="console-claude"><p className="console-claude-context">Image / {d.title} / v{d.versions}</p><form onSubmit={e => { e.preventDefault(); void ask(); }}><select aria-label="Image Claude action" value={intent} onChange={e => setIntent(e.target.value)}><option value="adjust">Adjustments</option><option value="select">Selection</option><option value="arrange">Arrange layers</option><option value="vector">Vector shapes</option></select><textarea autoFocus aria-label="Ask Claude about this image" value={prompt} maxLength={8000} onChange={e => setPrompt(e.target.value)} /><button className="console-primary" disabled={busy || dirty || !prompt.trim()}><MessageSquare size={16} />{busy ? 'Working...' : 'Ask Claude'}</button></form>{error && <p role="alert">{error}</p>}{answer && <p className="console-claude-answer">{answer}</p>}{proposal && <section className="console-proposal" aria-label="Proposed Image edit"><h3>Proposed edit</h3><pre>{JSON.stringify(proposal.args.action ?? proposal.args.shape, null, 2)}</pre><div><button className="console-primary" disabled={busy || dirty} onClick={() => void apply()}><Check size={16} />{proposal.command === 'console.image.selection' ? 'Apply selection' : 'Apply as new version'}</button><button className="console-plain" disabled={busy} onClick={() => setProposal(null)}><ArrowLeft size={15} />Discard proposal</button></div></section>}</div>;
}
