import { useEffect, useState } from 'react';
import { ArrowDown, ArrowUp, Copy, Eye, EyeOff, FolderPlus, Layers, Lock, Plus, Scan, Trash2, Unlock, X } from 'lucide-react';
import { IconButton } from '../Panels';
import { neutral, type Action, type Adjustments, type ImageRecord, type Layer, type Matrix, type Vector, type View } from './client';

interface Props { model: ImageRecord; view: View; busy: boolean; visible: boolean; edit(a: Action): Promise<void>; update(v: View): void; adjustment(values: Adjustments | null): void; pending(v: boolean): void }
function NumberField({ label, value, min, max, step, onChange }: { label: string; value: number; min?: number; max?: number; step?: number; onChange(n: number): void }) { return <label className="image-number">{label}<input aria-label={label} type="number" value={Number(value.toFixed(3))} min={min} max={max} step={step ?? 1} onChange={e => { const n = e.currentTarget.valueAsNumber; if (Number.isFinite(n)) onChange(n); }} /></label>; }
function Transform({ matrix, disabled, apply }: { matrix: Matrix; disabled: boolean; apply(m: Matrix): void }) {
  const [m, set] = useState(matrix);
  useEffect(() => set(matrix), [matrix]);
  const angle = Math.atan2(m.b, m.a) * 180 / Math.PI; const sx = Math.hypot(m.a, m.b); const sy = (m.a * m.d - m.b * m.c) / sx;
  const rotate = (angle: number, x = sx, y = sy) => { const a = angle * Math.PI / 180; set({ ...m, a: Math.cos(a) * x, b: Math.sin(a) * x, c: -Math.sin(a) * y, d: Math.cos(a) * y }); };
  return <fieldset disabled={disabled} className="image-transform"><legend>Transform</legend><div className="image-number-grid"><NumberField label="X" value={m.e} onChange={e => set({ ...m, e })} /><NumberField label="Y" value={m.f} onChange={f => set({ ...m, f })} /><NumberField label="Scale X" value={sx} step={0.1} min={0.01} onChange={x => rotate(angle, x, sy)} /><NumberField label="Scale Y" value={sy} step={0.1} min={0.01} onChange={y => rotate(angle, sx, y)} /><NumberField label="Angle" value={angle} onChange={rotate} /></div><button type="button" className="console-plain" onClick={() => apply(m)}>Apply transform</button></fieldset>;
}
function ObjectInspector({ object, layer, busy, edit }: { object: Vector; layer: Layer; busy: boolean; edit(a: Action): Promise<void> }) {
  const [o, set] = useState(object);
  useEffect(() => set(object), [object]);
  const apply = (next = o) => void edit({ type: 'vectorUpdate', layer: layer.id, object: next });
  return <fieldset className="image-object" disabled={busy || layer.locked}><legend>Object</legend>
    <input aria-label="Object name" value={o.name} maxLength={200} onChange={e => set({ ...o, name: e.target.value })} />
    <div className="image-style-row"><label><input type="checkbox" checked={o.fill !== null} onChange={e => set({ ...o, fill: e.target.checked ? '#171717' : null })} />Fill<input aria-label="Object fill" type="color" value={(o.fill ?? '#171717').slice(0, 7)} disabled={o.fill === null} onChange={e => set({ ...o, fill: e.target.value })} /></label><label><input type="checkbox" checked={o.stroke !== null} onChange={e => set({ ...o, stroke: e.target.checked ? '#171717' : null })} />Stroke<input aria-label="Object stroke" type="color" value={(o.stroke ?? '#171717').slice(0, 7)} disabled={o.stroke === null} onChange={e => set({ ...o, stroke: e.target.value })} /></label></div>
    <NumberField label="Stroke width" min={0} max={1000} value={o.strokeWidth} onChange={strokeWidth => set({ ...o, strokeWidth })} />
    <label>Object opacity<input aria-label="Object opacity" type="range" min={0} max={1} step={0.01} value={o.opacity} onChange={e => set({ ...o, opacity: Number(e.target.value) })} /></label>
    {(o.shape.type === 'rect' || o.shape.type === 'ellipse') && <div className="image-number-grid">{(['x', 'y', 'width', 'height'] as const).map(k => <NumberField key={k} label={`Object ${k}`} value={(o.shape as { x: number; y: number; width: number; height: number })[k]} min={k === 'width' || k === 'height' ? 1 : undefined} onChange={value => set({ ...o, shape: { ...o.shape, [k]: value } })} />)}{o.shape.type === 'rect' && <NumberField label="Corner radius" value={o.shape.radius} min={0} onChange={radius => set({ ...o, shape: { ...o.shape, radius } as Vector['shape'] })} />}</div>}
    {o.shape.type === 'text' && <><textarea aria-label="Object text" value={o.shape.text} onChange={e => set({ ...o, shape: { ...o.shape, text: e.target.value } as Vector['shape'] })} /><NumberField label="Font size" value={o.shape.size} min={1} max={1000} onChange={size => set({ ...o, shape: { ...o.shape, size } as Vector['shape'] })} /><select aria-label="Font family" value={o.shape.font} onChange={e => set({ ...o, shape: { ...o.shape, font: e.target.value } as Vector['shape'] })}><option>IBM Plex Serif</option><option>IBM Plex Mono</option></select></>}
    {o.shape.type === 'path' && <textarea aria-label="Vector path" value={o.shape.d} onChange={e => set({ ...o, shape: { type: 'path', d: e.target.value } })} />}
    <div className="image-small-actions"><button type="button" className="console-primary" onClick={() => apply()}>Apply object</button><IconButton label="Delete vector object" onClick={() => void edit({ type: 'vectorDelete', layer: layer.id, object: o.id })}><Trash2 size={15} /></IconButton></div>
    <Transform matrix={o.transform} disabled={busy || layer.locked} apply={transform => apply({ ...o, transform })} />
  </fieldset>;
}
export function ImageInspector({ model, view, busy, visible, edit, update, adjustment, pending }: Props) {
  const layer = model.layers.find(l => l.id === view.layer) ?? model.layers[0];
  const [values, setValues] = useState(layer.adjustments);
  const [opacity, setOpacity] = useState(layer.opacity);
  useEffect(() => setOpacity(layer.opacity), [layer.opacity, layer.id]);
  const [selectedCurve, setCurve] = useState(0);
  const [dimensions, setDimensions] = useState({ width: model.width, height: model.height });
  const [renaming, setRenaming] = useState<string | null>(null);
  const [name, setName] = useState('');
  useEffect(() => { setValues(layer.adjustments); adjustment(null); pending(false); setCurve(0); }, [layer.id, layer.adjustments]);
  useEffect(() => setDimensions({ width: model.width, height: model.height }), [model.width, model.height]);
  const setAdjustment = (next: Adjustments) => { setValues(next); adjustment(next); pending(JSON.stringify(next) !== JSON.stringify(layer.adjustments)); };
  const props = (patch: Record<string, unknown>) => void edit({ type: 'layer', layer: layer.id, ...patch });
  const move = (direction: -1 | 1) => { const siblings = model.layers.filter(l => l.parent === layer.parent); const at = siblings.indexOf(layer); const before = direction === -1 ? siblings[at - 1]?.id : siblings[at + 2]?.id ?? null; if (at + direction >= 0 && at + direction < siblings.length) void edit({ type: 'move', layer: layer.id, parent: layer.parent, before }); };
  const depth = (l: Layer): number => l.parent ? 1 + depth(model.layers.find(p => p.id === l.parent)!) : 0;
  const object = layer.objects?.find(o => o.id === view.object);
  const adjustmentDirty = JSON.stringify(values) !== JSON.stringify(layer.adjustments);
  return <aside className="image-inspector" aria-label="Image inspector" hidden={!visible}>
    <div className="image-inspector-heading"><h3>Layers</h3><IconButton label="Close image inspector" onClick={() => update({ inspector: false })}><X size={16} /></IconButton></div>
    <div className="image-small-actions"><IconButton label="Add pixel layer" disabled={busy} onClick={() => void edit({ type: 'add', kind: 'pixel', name: 'Pixel layer', parent: null })}><Plus size={16} /></IconButton><IconButton label="Add vector layer" disabled={busy} onClick={() => void edit({ type: 'add', kind: 'vector', name: 'Vector layer', parent: null })}><Scan size={16} /></IconButton><IconButton label="Add layer group" disabled={busy} onClick={() => void edit({ type: 'add', kind: 'group', name: 'Group', parent: null })}><FolderPlus size={16} /></IconButton><IconButton label="Duplicate layer" disabled={busy} onClick={() => void edit({ type: 'duplicate', layer: layer.id })}><Copy size={15} /></IconButton><IconButton label="Delete layer" disabled={busy || model.layers.length === 1} onClick={() => void edit({ type: 'delete', layer: layer.id })}><Trash2 size={15} /></IconButton></div>
    <ol className="image-layer-list">{model.layers.map(l => <li key={l.id} data-selected={layer.id === l.id} draggable={!busy} onDragStart={e => { e.dataTransfer.setData('application/wi-layer', l.id); e.dataTransfer.effectAllowed = 'move'; }} onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); const id = e.dataTransfer.getData('application/wi-layer'); if (id && id !== l.id) void edit({ type: 'move', layer: id, parent: l.parent, before: l.id }); }} style={{ paddingLeft: 4 + depth(l) * 12 }}>
      <button type="button" className="image-layer-name" onClick={() => update({ layer: l.id, object: null, mask: false })} onDoubleClick={() => { setRenaming(l.id); setName(l.name); }}><Layers size={13} /><span>{l.name}</span>{l.mask && <span className="image-mask-mark">M</span>}</button>
      <IconButton label={`${l.visible ? 'Hide' : 'Show'} ${l.name}`} disabled={busy} onClick={() => void edit({ type: 'layer', layer: l.id, visible: !l.visible })}>{l.visible ? <Eye size={13} /> : <EyeOff size={13} />}</IconButton><IconButton label={`${l.locked ? 'Unlock' : 'Lock'} ${l.name}`} disabled={busy} onClick={() => void edit({ type: 'layer', layer: l.id, locked: !l.locked })}>{l.locked ? <Lock size={13} /> : <Unlock size={13} />}</IconButton>
    </li>)}</ol>
    {renaming && <form className="image-small-actions" onSubmit={e => { e.preventDefault(); if (name.trim()) { void edit({ type: 'layer', layer: renaming, name }); setRenaming(null); } }}><input aria-label="Layer name" value={name} maxLength={200} onChange={e => setName(e.target.value)} /><button className="console-plain">Rename</button></form>}
<fieldset disabled={busy}><legend>{layer.name}</legend><div className="image-small-actions"><IconButton label="Move layer up" onClick={() => move(-1)}><ArrowUp size={15} /></IconButton><IconButton label="Move layer down" onClick={() => move(1)}><ArrowDown size={15} /></IconButton><select aria-label="Layer group" value={layer.parent ?? ''} onChange={e => void edit({ type: 'move', layer: layer.id, parent: e.target.value || null, before: null })}><option value="">Canvas</option>{model.layers.filter(l => l.type === 'group' && l.id !== layer.id).map(l => <option key={l.id} value={l.id}>{l.name}</option>)}</select></div><label>Opacity <output>{Math.round(opacity * 100)}%</output><input aria-label="Layer opacity" type="range" min={0} max={1} step={0.01} value={opacity} onChange={e => setOpacity(Number(e.target.value))} onPointerUp={e => props({ opacity: Number(e.currentTarget.value) })} onKeyUp={e => props({ opacity: Number(e.currentTarget.value) })} /></label><select aria-label="Blend mode" value={layer.blend} onChange={e => props({ blend: e.target.value })}>{['normal', 'multiply', 'screen', 'overlay', 'darken', 'lighten', 'difference'].map(s => <option key={s}>{s}</option>)}</select></fieldset>
    <Transform matrix={layer.transform} disabled={busy || layer.locked} apply={matrix => void edit({ type: 'transform', layer: layer.id, matrix })} />
    <fieldset disabled={busy || layer.locked}><legend>Mask</legend><div className="image-small-actions"><label><input type="checkbox" checked={!!view.mask} disabled={!layer.mask} onChange={e => update({ mask: e.target.checked })} />Edit mask</label><button className="console-plain" onClick={() => void edit({ type: 'mask', layer: layer.id, operation: 'add' })}>{layer.mask ? 'Replace' : 'Add'}</button>{layer.mask && <><button className="console-plain" onClick={() => void edit({ type: 'mask', layer: layer.id, operation: 'invert' })}>Invert</button><IconButton label="Remove mask" onClick={() => void edit({ type: 'mask', layer: layer.id, operation: 'remove' })}><Trash2 size={14} /></IconButton></>}</div></fieldset>
    {!!layer.objects?.length && <fieldset><legend>Vectors</legend><select aria-label="Selected vector object" value={view.object ?? ''} onChange={e => update({ object: e.target.value || null })}><option value="">Layer</option>{layer.objects.map(o => <option key={o.id} value={o.id}>{o.name}</option>)}</select></fieldset>}
    {object && <ObjectInspector object={object} layer={layer} busy={busy} edit={edit} />}
    <fieldset disabled={busy || layer.locked}><legend>Adjustments</legend>{(['exposure', 'contrast', 'saturation', 'temperature', 'tint'] as const).map(k => <label key={k} className="image-adjustment">{k[0].toUpperCase() + k.slice(1)}<output>{values[k].toFixed(k === 'exposure' ? 1 : 0)}</output><input aria-label={k[0].toUpperCase() + k.slice(1)} type="range" min={k === 'exposure' ? -5 : -100} max={k === 'exposure' ? 5 : 100} step={k === 'exposure' ? 0.1 : 1} value={values[k]} onChange={e => setAdjustment({ ...values, [k]: Number(e.target.value) })} /></label>)}
      <svg className="image-curve" viewBox="0 0 200 120" aria-label="Tone curve" role="img" onPointerDown={e => { if (busy || layer.locked) return; const r = e.currentTarget.getBoundingClientRect(); const x = Math.min(0.99, Math.max(0.01, (e.clientX - r.left) / r.width)); const y = Math.min(1, Math.max(0, 1 - (e.clientY - r.top) / r.height)); if (values.curves.length >= 16 || values.curves.some(p => Math.abs(p[0] - x) < 0.015)) return; const curves = [...values.curves, [x, y] as [number, number]].sort((a, b) => a[0] - b[0]); setCurve(curves.findIndex(p => p[0] === x)); setAdjustment({ ...values, curves }); }}><path d="M0 120L200 0" stroke="var(--console-line)" /><polyline fill="none" stroke="currentColor" strokeWidth={2} points={values.curves.map(([x, y]) => `${x * 200},${120 - y * 120}`).join(' ')} />{values.curves.map(([x, y], i) => <circle key={i} cx={x * 200} cy={120 - y * 120} r={i === selectedCurve ? 5 : 3} fill={i === selectedCurve ? '#407bd0' : 'currentColor'} onPointerDown={e => { e.stopPropagation(); setCurve(i); }} />)}</svg>
      <div className="image-small-actions"><NumberField label="Curve output" value={values.curves[selectedCurve]?.[1] ?? 0} min={0} max={1} step={0.01} onChange={y => { const curves = values.curves.map((p, i) => i === selectedCurve ? [p[0], Math.max(0, Math.min(1, y))] as [number, number] : p); setAdjustment({ ...values, curves }); }} /><IconButton label="Remove curve point" disabled={selectedCurve === 0 || selectedCurve === values.curves.length - 1} onClick={() => { setAdjustment({ ...values, curves: values.curves.filter((_, i) => i !== selectedCurve) }); setCurve(0); }}><Trash2 size={14} /></IconButton></div>
      <div className="image-small-actions"><button type="button" className="console-primary" disabled={!adjustmentDirty} onClick={() => void edit({ type: 'adjust', layer: layer.id, values })}>Apply adjustments</button><button type="button" className="console-plain" onClick={() => setAdjustment(neutral())}>Reset</button></div>
    </fieldset>
    <fieldset disabled={busy}><legend>Canvas</legend><div className="image-number-grid"><NumberField label="Canvas width" value={dimensions.width} min={1} max={8192} onChange={width => setDimensions({ ...dimensions, width })} /><NumberField label="Canvas height" value={dimensions.height} min={1} max={8192} onChange={height => setDimensions({ ...dimensions, height })} /></div><button type="button" className="console-plain" onClick={() => void edit({ type: 'resize', ...dimensions })}>Resize</button><label><input type="checkbox" checked={model.background !== null} onChange={e => void edit({ type: 'background', color: e.target.checked ? '#ffffff' : null })} />Background<input aria-label="Canvas background" type="color" value={(model.background ?? '#ffffff').slice(0, 7)} disabled={!model.background} onChange={e => void edit({ type: 'background', color: e.target.value })} /></label></fieldset>
  </aside>;
}
