[package]
name = "wi-heat"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
jiff = { version = "0.2", default-features = false, features = ["std", "tzdb-bundle-always"] }
rand.workspace = true
regex = "1"
serde.workspace = true
serde_json.workspace = true
wwav-ids.workspace = true

[dev-dependencies]
proptest.workspace = true
