import { test, expect, type Page } from '@playwright/test';
import { readFile } from 'node:fs/promises';

async function core(cmd: string, args: Record<string, unknown> = {}): Promise<any> {
  const ws = new WebSocket('ws://127.0.0.1:8795');
  return new Promise((resolve, reject) => { const timer = setTimeout(() => { ws.close(); reject(new Error(`Timed out: ${cmd}`)); }, 60000); ws.onopen = () => ws.send(JSON.stringify({ id: 1, cmd, args })); ws.onerror = () => { clearTimeout(timer); reject(new Error('Core failed')); }; ws.onmessage = e => { const r = JSON.parse(String(e.data)); if (r.id !== 1) return; clearTimeout(timer); ws.close(); r.ok ? resolve(r.result) : reject(new Error(r.error.message)); }; });
}
async function create(page: Page, title: string) {
  await page.goto('/console.html'); await expect(page.getByRole('tab', { name: 'Image', exact: true })).toBeEnabled(); await page.getByRole('tab', { name: 'Image', exact: true }).click(); await page.locator('.console-top-actions').getByRole('button', { name: 'New document', exact: true }).click(); await page.getByRole('dialog').getByLabel('Title', { exact: true }).fill(title); await page.getByRole('button', { name: 'Create document', exact: true }).click(); await expect(page.getByRole('dialog')).toHaveCount(0); await expect(page.getByRole('img', { name: title, exact: true })).toBeVisible();
  if (await page.getByRole('button', { name: 'Close Library' }).isVisible()) await page.getByRole('button', { name: 'Close Library' }).click();
  if (await page.getByRole('button', { name: 'Close image inspector' }).isVisible()) await page.getByRole('button', { name: 'Close image inspector' }).click();
}
async function data(title: string) { const l = await core('console.library', { tool: 'image' }); const d = l.documents.find((d: any) => d.title === title); return core('console.image.read', { id: d.id }); }
async function drag(page: Page, ax: number, ay: number, bx: number, by: number) { const img = await page.locator('.image-document:visible .image-artboard > img').first().boundingBox(); await page.mouse.move(img!.x + ax * img!.width, img!.y + ay * img!.height); await page.mouse.down(); await page.mouse.move(img!.x + bx * img!.width, img!.y + by * img!.height, { steps: 12 }); await page.mouse.up(); await expect(page.locator('.image-document:visible .image-processing')).toHaveCount(0); }

test('make a mixed-layer poster, version, fork, inspect and export every format', async ({ page }) => {
  test.setTimeout(120000); const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await create(page, 'A little light');
  await page.locator('.image-document:visible').getByLabel('Paint color').fill('#407bd0'); await page.locator('.image-document:visible').getByLabel('Brush size').fill('100'); await drag(page, 0.2, 0.25, 0.78, 0.72);
  let r = await data('A little light'); expect(r.document.versions).toBe(2); expect(r.image.layers[0].type).toBe('pixel');
  await page.getByRole('button', { name: 'Ellipse', exact: true }).click(); await page.locator('.image-document:visible').getByLabel('Paint color').fill('#e4c84a'); await drag(page, 0.35, 0.18, 0.67, 0.72);
  r = await data('A little light'); expect(r.image.layers[0].type).toBe('vector'); expect(r.image.layers[0].objects[0].shape.type).toBe('ellipse');
  await page.getByRole('button', { name: 'Text', exact: true }).click(); const img = await page.locator('.image-artboard:visible').boundingBox(); await page.mouse.click(img!.x + img!.width * 0.13, img!.y + img!.height * 0.8); await page.locator('.image-document:visible').getByLabel('Canvas text').fill('A LITTLE LIGHT'); await page.getByRole('button', { name: 'Place text', exact: true }).click(); await expect(page.locator('.image-processing:visible')).toHaveCount(0);
  await page.getByRole('button', { name: 'Toggle image inspector' }).click(); await expect(page.locator('.image-document:visible').getByLabel('Selected vector object')).toBeVisible(); await expect(page.locator('.image-document:visible').getByLabel('Object text')).toHaveValue('A LITTLE LIGHT'); await page.locator('.image-document:visible').getByLabel('Object fill').fill('#171717'); await page.getByRole('button', { name: 'Apply object', exact: true }).click(); await expect(page.locator('.image-processing:visible')).toHaveCount(0);
  await page.getByRole('button', { name: 'Close image inspector' }).click(); await page.screenshot({ path: '/private/tmp/console-image-poster.png' });
  const ink = await page.getByRole('img', { name: 'A little light', exact: true }).evaluate((img: HTMLImageElement) => { const c = document.createElement('canvas'); c.width = 256; c.height = 144; const ctx = c.getContext('2d')!; ctx.drawImage(img, 0, 0, 256, 144); const p = ctx.getImageData(0, 0, 256, 144).data; return Array.from(p).filter((v, i) => i % 4 === 3 && v > 0).length; }); expect(ink).toBeGreaterThan(1000);
  for (const format of ['png', 'jpg', 'svg', 'pdf']) { await page.locator('.image-document:visible').getByLabel('Image export format').selectOption(format); const waiting = page.waitForEvent('download'); await page.getByRole('button', { name: 'Export image', exact: true }).click(); const f = await waiting; const bytes = await readFile((await f.path())!); expect(bytes.length).toBeGreaterThan(100); if (format === 'svg') { expect(bytes.toString()).toContain('<text'); expect(bytes.toString()).toContain('data:image/png;base64,'); } if (format === 'pdf') expect(bytes.subarray(0, 8).toString()).toBe('%PDF-1.7'); await expect(page.getByRole('button', { name: 'Export image', exact: true })).toBeEnabled(); }
  await page.getByRole('button', { name: 'Save as variation', exact: true }).click(); await page.getByRole('dialog').getByLabel('Title', { exact: true }).fill('Another light'); await page.getByRole('button', { name: 'Create variation', exact: true }).click(); await expect(page.getByRole('dialog')).toHaveCount(0); await expect(page.locator('.image-document:visible').getByLabel('Document title', { exact: true })).toHaveValue('Another light'); expect((await data('Another light')).image.layers.length).toBe(2);
  await page.getByRole('button', { name: 'Read saved version' }).click(); await expect(page.getByRole('dialog').getByRole('img', { name: 'Another light', exact: true })).toBeVisible(); await page.getByRole('button', { name: 'Close Reader' }).click();
  await page.getByRole('tab', { name: 'Write', exact: true }).click(); await page.getByRole('tab', { name: 'Image', exact: true }).click(); await expect(page.locator('.image-document:visible').getByLabel('Document title', { exact: true })).toHaveValue('Another light');
  expect(errors).toEqual([]);
});

test('selection masks, adjustments, Claude, undo and compact viewport use saved Rust edits', async ({ page }) => {
  test.setTimeout(120000); await create(page, 'Photo study');
  const svg = '<svg xmlns="http://www.w3.org/2000/svg" width="800" height="600"><rect width="800" height="600" fill="#658d84"/><circle cx="360" cy="280" r="150" fill="#e4c84a"/><path d="M0 500L800 200V600H0Z" fill="#407bd0"/></svg>';
  const imported = await core('console.import', { name: 'photo-source.svg', base64: Buffer.from(svg).toString('base64') }); const raster = await core('console.image.export', { id: imported.document.id, format: 'jpg' }); await core('console.open', { id: (await data('Photo study')).document.id }); await page.locator('.image-document:visible input[aria-label="Image layer file"]').setInputFiles({ name: 'study.jpg', mimeType: 'image/jpeg', buffer: Buffer.from(raster.base64, 'base64') }); await expect(page.locator('.image-processing:visible')).toHaveCount(0);
  await page.getByRole('button', { name: 'Rectangle selection', exact: true }).click(); await drag(page, 0.25, 0.2, 0.75, 0.8); await page.getByRole('button', { name: 'Toggle image inspector' }).click(); await page.getByRole('button', { name: 'Add', exact: true }).click(); await expect(page.locator('.image-processing:visible')).toHaveCount(0); expect((await data('Photo study')).image.layers[0].mask).not.toBeNull();
  await page.locator('.image-document:visible').getByLabel('Exposure', { exact: true }).fill('0.6'); await expect(page.locator('.console-version-label:visible')).toContainText('Unsaved'); await page.getByRole('button', { name: 'Apply adjustments', exact: true }).click(); await expect(page.getByRole('button', { name: 'Save version', exact: true })).toBeEnabled();
  await page.getByRole('button', { name: 'Ask Claude', exact: true }).click(); const dialog = page.getByRole('dialog', { name: 'Claude', exact: true }); await dialog.getByLabel('Ask Claude about this image').fill('Warmer, softer contrast'); await dialog.getByRole('button', { name: 'Ask Claude', exact: true }).click(); await expect(dialog.getByRole('region', { name: 'Proposed Image edit' })).toContainText('temperature'); const before = await data('Photo study'); await dialog.getByRole('button', { name: 'Apply as new version' }).click(); await expect(dialog).toContainText('Applied as a new version.'); await page.getByRole('button', { name: 'Close Claude', exact: true }).click(); await expect(page.locator('.image-document:visible .console-provenance')).toHaveText('Claude assisted');
  await page.getByRole('button', { name: 'Undo document edit' }).click(); const after = await data('Photo study'); expect(after.image.layers[0].adjustments).toEqual(before.image.layers[0].adjustments);
  await page.setViewportSize({ width: 390, height: 844 }); await page.getByRole('button', { name: 'Close image inspector' }).click(); await expect(page.getByRole('img', { name: 'Photo study', exact: true })).toBeVisible(); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); await page.getByRole('button', { name: 'Zoom in', exact: true }).click(); await page.getByRole('button', { name: 'Rotate canvas view', exact: true }).click(); await page.screenshot({ path: '/private/tmp/console-image-mobile.png' });
});

test('a sixteen-megapixel canvas keeps navigation on animation frames', async ({ page }) => {
  test.setTimeout(180000); await create(page, 'Large image'); let r = await data('Large image');
  const start = performance.now(); await core('console.image.edit', { id: r.document.id, base: r.base, action: { type: 'resize', width: 4096, height: 4096 } }); await expect(page.locator('.image-document:visible .console-document-foot')).toContainText('4096 x 4096'); const saved = performance.now() - start;
  r = await data('Large image'); expect(r.preview.width).toBeLessThanOrEqual(1536);
  const full = await core('console.image.export', { id: r.document.id, format: 'png' });
  const importStart = performance.now(); await core('console.image.edit', { id: r.document.id, base: r.base, action: { type: 'import', name: '4096-pixel-layer.png', base64: full.base64, fit: true } }); r = await data('Large image'); const importedMs = performance.now() - importStart;
  const measurements = await page.evaluate(async () => { const viewport = document.querySelector('.image-document:not([hidden]) .image-viewport')!; const times: number[] = []; for (let i = 0; i < 24; i++) { const t = performance.now(); viewport.dispatchEvent(new WheelEvent('wheel', { deltaX: 8, deltaY: 6, bubbles: true, cancelable: true })); await new Promise<void>(resolve => requestAnimationFrame(() => resolve())); times.push(performance.now() - t); } return times; });
  console.log('Image performance sample:', JSON.stringify({ pixels: 16777216, resizeAndPreviewMs: Math.round(saved), fullPixelImportSavePreviewMs: Math.round(importedMs), panFrameP95Ms: measurements.sort((a, b) => a - b)[22] })); expect(measurements[22]).toBeLessThan(100); await page.screenshot({ path: '/private/tmp/console-image-large.png' });
});

test('Bezier pen, object transforms, groups, locks and eraser are available from the canvas', async ({ page }) => {
  test.setTimeout(120000); await create(page, 'A curve'); await page.getByRole('button', { name: 'Vector pen', exact: true }).click();
await drag(page, 0.2, 0.3, 0.28, 0.15); await drag(page, 0.5, 0.5, 0.6, 0.65); await drag(page, 0.8, 0.3, 0.8, 0.3); await page.locator('.image-document:visible').getByLabel('Image canvas', { exact: true }).focus(); await page.keyboard.press('Enter');
  await expect(page.locator('.image-processing:visible')).toHaveCount(0); const r = await data('A curve'); expect(r.image.layers[0].objects[0].shape.d).toContain('C');
  await page.getByRole('button', { name: 'Toggle image inspector' }).click(); await expect(page.getByRole('textbox', { name: 'Vector path', exact: true })).toBeVisible(); const vectorId = r.image.layers[0].id;
  await page.getByRole('button', { name: 'Add layer group', exact: true }).click(); await expect(page.locator('.image-processing:visible')).toHaveCount(0); const grouped = await data('A curve'); const groupId = grouped.image.layers[0].id;
  await core('console.image.edit', { id: grouped.document.id, base: grouped.base, action: { type: 'move', layer: vectorId, parent: groupId, before: null } }); await expect(page.locator('.image-document:visible .console-version-label')).toHaveText(`v${grouped.document.versions + 1}`); await expect(page.getByRole('button', { name: 'Lock Group', exact: true })).toBeEnabled();
  await page.getByRole('button', { name: 'Lock Group', exact: true }).click(); await expect(page.getByRole('button', { name: 'Unlock Group', exact: true })).toBeVisible(); await page.getByRole('button', { name: 'Unlock Group', exact: true }).click(); await page.getByRole('button', { name: 'Close image inspector' }).click(); await page.getByRole('button', { name: 'Brush', exact: true }).click(); await drag(page, 0.2, 0.8, 0.6, 0.8); await page.getByRole('button', { name: 'Eraser', exact: true }).click(); await drag(page, 0.2, 0.8, 0.6, 0.8); await page.screenshot({ path: '/private/tmp/console-image-pen.png' });
});
